import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Header from "./Header/page";
import Footer from "./Footer/page"; 
const nacyFont = localFont({
  src: "../../public/Font/nacy.ttf",
  variable: "--font-nacy",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nacyFont.variable} antialiased`}
      >
        <div className="px-4 md:px-16"><Header/></div>
        
        {children}
         <div><Footer/></div>
      </body>
    </html>
  );
}
